### ISSUE TITLE
npm ERR! No valid versions available for edge

### ISSUE THREAD

**Issue by Alexandre-Rosati** [aca-labs/skype-native#3] opened 2018-06-05 14:57 UTC
hello,

I tried to install this package via npm and i had this problem : 

$ npm install acaprojects/skype-native
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for edge

can we find a solution ? :)

Ty 

[2018-06-05T14_52_58_728Z-debug.log](https://github.com/acaprojects/skype-native/files/2072864/2018-06-05T14_52_58_728Z-debug.log)

**Comment by kimburgess** [comment] 2018-06-05 18:18
Thanks for the report!

It looks like there's an [issue that impact NPM v5.5.1](https://github.com/npm/npm/issues/3328#issuecomment-367016782) which breaks resolution of semver git references. This appears to be fixed in current releases so after an upgrade there you should be in action.

Looking at the logs it's [this dependancy](https://github.com/acaprojects/edge-ts/blob/master/package.json#L58) over in the edge-ts repo that it's complaining about, however that resource to [definitely still exists](https://github.com/tjanczuk/edge/releases/tag/v8.2.1). I'm also unable to reproduce here with NPM v5.6.0 so fairly confident that it's the above. With that in mind I'll close this off for now, but feel free to reopen if it persists.

**Closed as completed by kimburgess** 2018-06-05 18:18 UTC
